apiVersion: apps/v1
kind: Deployment
metadata:
    name: inventory-app-deployment
    namespace: kubernetes-cluster-dikshasingla
    labels:
        app: inventory-app
spec:
    replicas: 4
    selector:
        matchLabels:
            app: inventory-app
    template:
        metadata:
            labels:
                app: inventory-app
        spec:
            containers:
                - name: inventory-app
                  image: dikshasingla/inventory:latest-develop
                  ports:
                    - name: http
                      containerPort: 3515
                      protocol: TCP
