kind: Namespace
apiVersion: v1
metadata:
    name: kubernetes-cluster-dikshasingla
    labels:
        name: kubernetes-cluster-dikshasingla

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: java-app-deployment
    namespace: kubernetes-cluster-dikshasingla
    labels:
        app: java-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: java-app
    template:
        metadata:
            labels:
                app: java-app
        spec:
            containers:
                - name: java-app
                  image: dikshasingla/inventory:latest
                  ports:
                    - name: http
                      containerPort: 3515
                      protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: java-app
    namespace: kubernetes-cluster-dikshasingla
spec:
    type: NodePort
    selector:
        app: java-app
    ports:
        - protocol: TCP
          nodePort: 30158
          port: 80
          targetPort: 3515