apiVersion: v1
kind: Service
metadata: 
    name: inventory-app
    namespace: kubernetes-cluster-dikshasingla
    labels:
        app: inventory-app
spec:
    type: NodePort
    selector:
        app: inventory-app
    ports:
        - protocol: TCP
          nodePort: 30158
          port: 80
          targetPort: 3515